runtime: go122
service: default
app_engine_apis: true

env_variables:
  FIRESTORE_PROJECT_ID: "esperanto-kurso"
  WEBAUTHN_RPID: "esperanto-kurso.net"
  WEBAUTHN_ORIGIN: "https://esperanto-kurso.net"

handlers:
  - url: /static
    static_dir: static
  - url: /admin/initial
    script: auto
    login: admin
  - url: /.*
    script: auto
