package eo

const (
	SiteTitle        = "Esperanto-kurso"
	NavHome          = "Hejmo"
	NavSave          = "Konservu progreson"
	NavAdmin         = "Administrado"
	ExerciseCorrect  = "Ĝuste!"
	ExerciseIncorrect = "Malĝuste."
	ExerciseSubmit   = "Sendi"
	ExerciseNext     = "Sekva ekzerco"
	ExerciseHint     = "Indiko"
	LoadingMsg       = "Ŝarĝas..."
	SaveProgress     = "Konservu vian progreson"
	MagicLinkLabel   = "Via sekreta ligo"
	PasskeyRegister  = "Registri ensalutŝlosilon"
	PasskeyLogin     = "Ensaluti per ensalutŝlosilo"
	AdminDashboard   = "Administra panelo"
	AdminContent     = "Enhavo"
	AdminModeration  = "Moderado"
	AdminNewContent  = "Nova enhavo"
	ContentApprove   = "Aprobi"
	ContentReject    = "Malakcepti"
	VoteUp           = "Voĉdoni supren"
	VoteDown         = "Voĉdoni malsupren"
	CommentAdd       = "Aldoni komenton"
	CommentSubmit    = "Sendi"
	RatingLabel      = "Nivelo"
	CorrectAnswer    = "Ĝusta respondo"
	YourAnswer       = "Via respondo"
	MultipleChoice   = "Elektu la ĝustan respondon"
	FillInBlank      = "Plenigi la blankon"
	ListeningExercise = "Aŭskultu kaj respondu"
	VocabExercise    = "Vortaro"
	ReadingExercise  = "Legado"
	PhraseBook       = "Frazaro"
	ImageExercise    = "Kion vidas vi?"
	StatusDraft      = "Malneto"
	StatusPending    = "Atendanta"
	StatusApproved   = "Aprobita"
	StatusRejected   = "Malakceptita"
)
